import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default tseslint.config(
  { ignores: ['dist', 'node_modules', 'coverage', 'src/app/public/service-worker.js', 'src/imports/**'] },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: { ecmaVersion: 2022, globals: { ...globals.browser, ...globals.node } },
    plugins: { 'react-hooks': reactHooks, 'react-refresh': reactRefresh, 'jsx-a11y': jsxA11y },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.configs.recommended.rules,
      'react-refresh/only-export-components': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-empty-object-type': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
  // Generated code: lint new/redesigned surfaces strictly, legacy pages leniently until each is redesigned
  {
    files: ['src/app/pages/**', 'src/app/components/**', 'src/app/utils/**', 'src/app/hooks/**', 'src/app/data/**', 'src/app/mocks/**', 'src/app/contexts/**', 'src/app/services/**', 'src/app/*.ts', 'src/app/*.tsx'],
    ignores: ['src/app/components/primitives/**', 'src/app/features/**'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',
      'jsx-a11y/no-noninteractive-element-interactions': 'off',
      'jsx-a11y/label-has-associated-control': 'off',
      'jsx-a11y/media-has-caption': 'off',
      'jsx-a11y/no-autofocus': 'off',
      'jsx-a11y/anchor-is-valid': 'off',
      'jsx-a11y/heading-has-content': 'off',
      'jsx-a11y/anchor-has-content': 'off',
      'jsx-a11y/no-noninteractive-tabindex': 'off',
      'jsx-a11y/interactive-supports-focus': 'off',
      'jsx-a11y/role-supports-aria-props': 'off',
      'jsx-a11y/no-redundant-roles': 'off',
      'jsx-a11y/aria-role': 'off',
      'jsx-a11y/alt-text': 'off',
      'jsx-a11y/img-redundant-alt': 'off',
      'jsx-a11y/no-noninteractive-element-to-interactive-role': 'off',
      'jsx-a11y/mouse-events-have-key-events': 'off',
      'jsx-a11y/tabindex-no-positive': 'off',
      'jsx-a11y/iframe-has-title': 'off',
      'jsx-a11y/scope': 'off',
      'jsx-a11y/no-distracting-elements': 'off',
      'jsx-a11y/aria-props': 'off',
      'jsx-a11y/aria-proptypes': 'off',
      'jsx-a11y/prefer-tag-over-role': 'off',
      'jsx-a11y/control-has-associated-label': 'off',
      'jsx-a11y/html-has-lang': 'off',
      'jsx-a11y/no-aria-hidden-on-focusable': 'off',
      'jsx-a11y/autocomplete-valid': 'off',
      'jsx-a11y/no-access-key': 'off',
      'jsx-a11y/lang': 'off',
      'jsx-a11y/aria-activedescendant-has-tabindex': 'off',
      'jsx-a11y/aria-unsupported-elements': 'off',
      'jsx-a11y/role-has-required-aria-props': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      'no-useless-escape': 'off',
      'no-prototype-builtins': 'off',
      'no-case-declarations': 'off',
      'no-constant-binary-expression': 'off',
      'no-constant-condition': 'off',
      'prefer-const': 'off',
      'no-unsafe-optional-chaining': 'off',
      'no-fallthrough': 'off',
      'no-async-promise-executor': 'off',
      'no-control-regex': 'off',
      'no-undef': 'off',
      'no-unused-vars': 'off',
      'no-cond-assign': 'off',
      'no-func-assign': 'off',
      'no-import-assign': 'off',
      'no-self-assign': 'off',
      'no-unreachable': 'off',
      'no-redeclare': 'off',
      'no-dupe-keys': 'off',
      'no-dupe-else-if': 'off',
      'no-duplicate-case': 'off',
      'no-empty-pattern': 'off',
      'no-sparse-arrays': 'off',
      'no-loss-of-precision': 'off',
      'no-misleading-character-class': 'off',
      'no-irregular-whitespace': 'off',
      'no-useless-catch': 'off',
      'no-extra-boolean-cast': 'off',
      'no-regex-spaces': 'off',
      'no-shadow-restricted-names': 'off',
      'no-global-assign': 'off',
      'no-unsafe-finally': 'off',
      'no-unsafe-negation': 'off',
      'no-with': 'off',
      'use-isnan': 'off',
      'valid-typeof': 'off',
      'getter-return': 'off',
      'for-direction': 'off',
      'no-compare-neg-zero': 'off',
      'no-debugger': 'off',
      'no-delete-var': 'off',
      'no-dupe-args': 'off',
      'no-dupe-class-members': 'off',
      'no-ex-assign': 'off',
      'no-inner-declarations': 'off',
      'no-invalid-regexp': 'off',
      'no-new-native-nonconstructor': 'off',
      'no-nonoctal-decimal-escape': 'off',
      'no-obj-calls': 'off',
      'no-octal': 'off',
      'no-setter-return': 'off',
      'no-unexpected-multiline': 'off',
      'no-unused-labels': 'off',
      'no-unused-private-class-members': 'off',
      'no-useless-backreference': 'off',
      'require-yield': 'off',
      'no-class-assign': 'off',
      'no-const-assign': 'off',
      'no-empty-character-class': 'off',
      'no-this-before-super': 'off',
      'constructor-super': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-wrapper-object-types': 'off',
      '@typescript-eslint/prefer-as-const': 'off',
      '@typescript-eslint/no-duplicate-enum-values': 'off',
      '@typescript-eslint/no-array-constructor': 'off',
      '@typescript-eslint/no-extra-non-null-assertion': 'off',
      '@typescript-eslint/no-misused-new': 'off',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'off',
      '@typescript-eslint/no-unnecessary-type-constraint': 'off',
      '@typescript-eslint/no-unsafe-declaration-merging': 'off',
      '@typescript-eslint/triple-slash-reference': 'off',
      '@typescript-eslint/prefer-namespace-keyword': 'off',
    },
  },
);
