// Emits dist/tokens.css from the compiled token module so web and native share one source.
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const { toCssVariables, palette } = await import(join(here, '..', 'dist', 'index.js'));

const block = (selector, vars) =>
  `${selector} {\n${Object.entries(vars)
    .map(([k, v]) => `  ${k}: ${v};`)
    .join('\n')}\n}\n`;

const paletteVars = {};
for (const [name, ramp] of Object.entries(palette)) {
  if (typeof ramp === 'string') continue;
  for (const [step, hex] of Object.entries(ramp)) paletteVars[`--${name}-${step}`] = hex;
}

const css =
  `/* Generated by @ezyify/tokens — do not edit. Source: packages/tokens/tokens.json */\n` +
  block(':root', { ...paletteVars, ...toCssVariables('light') }) +
  block('.dark', toCssVariables('dark'));

mkdirSync(join(here, '..', 'dist'), { recursive: true });
writeFileSync(join(here, '..', 'dist', 'tokens.css'), css);
console.log('tokens.css written');
